# Configuration file for the sensors on the system

ADC_CONFIG:
  i2c_addresses:
    b1: [0x6E,0x6F]   # I2C address for board 1
    b2: [0,0]         # I2C address PLACEHOLDER for board 2
    # ...

  pga_gain: 1
  # Set the gain of the PGA on the chip
  # Parameters: gain - 1, 2, 4, 8

  bit_rate: 16
  # Parameters: rate - 12, 14, 16, 18. Samples Per Second (SPS)
  # 12 = 12 bit (240SPS max)
  # 14 = 14 bit (60SPS max)
  # 16 = 16 bit (15SPS max)
  # 18 = 18 bit (3.75SPS max)

  conversion_mode: 1
  # Set the conversion mode for the ADC
  # Parameters: mode - 0 = One-shot conversion, 1 = Continuous conversion

  # (One-shot conversion) Perform a single conversion upon trigger, conserving power and resources for infrequent measurements
  # (Continuous conversion) Continuously convert analog signals to digital, suitable for real-time monitoring

#--------------------------------------------------------------

RPM_SENSORS:
  RPM_pump:
    GPIO pin: 21
    magnets: 14


ANGLE_SENSORS:
  sensor1:
    name: "LiftBoom"
    input: [ b1,8 ]               # [Board number, Port number]
    steps_per_revolution: 360     # Steps per revolution to improve accuracy


PRESSURE_SENSORS:
  sensor1:
    name: "Pump"                  # Name
    input: [b1,1]                 # [Board number, Port number]
    calibration_value: 1.000      # Multiplier for calibrating measurements

  sensor5:
    name: "LiftBoom extension"
    input: [b1,5]
    calibration_value: 1.000

  sensor6:
    name: "LiftBoom retraction"
    input: [b1,6]
    calibration_value: 1.000
